language: go
rvm:
  - 1.9.3
install:
  - go get github.com/shaoshing/gotest
  - go get github.com/ProductHealth/train
  - go get github.com/ProductHealth/train/interpreter
  - gem in sass
  - gem in coffee-script
script:
  ./test_all.sh
